apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: granular-mean-reference-upload
  labels:
    app.kubernetes.io/component: reference-upload
    app.kubernetes.io/name: granular-mean-reference
    app.kubernetes.io/part-of: granular-mean
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: reference-upload
      app.kubernetes.io/name: granular-mean-reference
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
